const nationInfos = [
	{ cc: 'kr', imageUrl: '/img/kr.svg', cn: 'South Korea' },
	{ cc: 'ad', imageUrl: '/img/ad.svg', cn: 'Andorra' },
	{ cc: 'ru', imageUrl: '/img/ru.svg', cn: 'Russia' },
	{ cc: 'af', imageUrl: '/img/af.svg', cn: 'Afghanistan' },
	{ cc: 'se', imageUrl: '/img/se.svg', cn: 'Sweden' },
	{ cc: 'ca', imageUrl: '/img/ca.svg', cn: 'Canada' },
	{ cc: 'ch', imageUrl: '/img/ch.svg', cn: 'Switzerland' },
	{ cc: 'cn', imageUrl: '/img/cn.svg', cn: 'China' },
	{ cc: 'de', imageUrl: '/img/de.svg', cn: 'German' },
	{ cc: 'dk', imageUrl: '/img/dk.svg', cn: 'Denmark' },
	{ cc: 'eg', imageUrl: '/img/eg.svg', cn: 'Egypt' },
	{ cc: 'es', imageUrl: '/img/es.svg', cn: 'Spain' },
	{ cc: 'fi', imageUrl: '/img/fi.svg', cn: 'Finland' },
	{ cc: 'fr', imageUrl: '/img/fr.svg', cn: 'France' },
	{ cc: 'hk', imageUrl: '/img/hk.svg', cn: 'Hongkong' },
	{ cc: 'id', imageUrl: '/img/id.svg', cn: 'Indonesia' },
	{ cc: 'ie', imageUrl: '/img/ie.svg', cn: 'Ireland' },
	{ cc: 'tw', imageUrl: '/img/tw.svg', cn: 'Taiwan' },
	{ cc: 'it', imageUrl: '/img/it.svg', cn: 'Italy' },
	{ cc: 'jp', imageUrl: '/img/jp.svg', cn: 'Japan' },
	{ cc: 'be', imageUrl: '/img/be.svg', cn: 'Belgium' },
	{ cc: 'ye', imageUrl: '/img/ye.svg', cn: 'Yemen' },
	{ cc: 'bg', imageUrl: '/img/bg.svg', cn: 'Bulgaria' },
	{ cc: 'bh', imageUrl: '/img/bh.svg', cn: 'Bahrain' },
	{ cc: 'bi', imageUrl: '/img/bi.svg', cn: 'Burundi' },
	{ cc: 'bj', imageUrl: '/img/bj.svg', cn: 'Benin' },
	{ cc: 've', imageUrl: '/img/ve.svg', cn: 'Venezuela' },
	{ cc: 'bm', imageUrl: '/img/bm.svg', cn: 'Bermuda' },
	{ cc: 'bn', imageUrl: '/img/bn.svg', cn: 'Brunei' },
	{ cc: 'bo', imageUrl: '/img/bo.svg', cn: 'Bolivia' },
	{ cc: 'ua', imageUrl: '/img/ua.svg', cn: 'Ukraine' },
	{ cc: 'br', imageUrl: '/img/br.svg', cn: 'Brazil' },
	{ cc: 'uy', imageUrl: '/img/uy.svg', cn: 'Uruguay' },
	{ cc: 'bt', imageUrl: '/img/bt.svg', cn: 'Bhutan' },
	{ cc: 'no', imageUrl: '/img/no.svg', cn: 'Norway' },
	{ cc: 'us', imageUrl: '/img/us.svg', cn: 'USA' },
];

export default nationInfos;
